[project]
name = "lightshow"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "audioread>=3.0.1",
    "certifi>=2025.7.14",
    "cffi>=1.17.1",
    "charset-normalizer>=3.4.2",
    "contourpy>=1.3.2",
    "cycler>=0.12.1",
    "decorator>=5.2.1",
    "dearpygui>=2.1.0",
    "fonttools>=4.59.0",
    "idna>=3.10",
    "joblib>=1.5.1",
    "kiwisolver>=1.4.8",
    "lazy-loader>=0.4",
    "librosa>=0.11.0",
    "llvmlite>=0.44.0",
    "msgpack>=1.1.1",
    "numba>=0.61.2",
    "numpy>=2.2.6",
    "packaging>=25.0",
    "pillow>=11.3.0",
    "platformdirs>=4.3.8",
    "pooch>=1.8.2",
    "pyaudio>=0.2.14",
    "pyaudiowpatch>=0.2.12.7",
    "pycparser>=2.22",
    "pyparsing>=3.2.3",
    "python-dateutil>=2.9.0.post0",
    "requests>=2.32.4",
    "scikit-learn>=1.7.1",
    "scipy>=1.16.0",
    "six>=1.17.0",
    "soundfile>=0.13.1",
    "soxr>=0.5.0.post1",
    "threadpoolctl>=3.6.0",
    "typing-extensions>=4.15.0",
    "urllib3>=2.5.0",
    "websocket-client>=1.8.0",
    "winrt-runtime>=3.2.1",
    "winrt-windows-media>=3.2.1",
    "winrt-windows-media-control>=3.2.1",
    "winrt-windows-foundation>=3.2.1",
    "winrt-windows-foundation-collections>=3.2.1",
    "pyinstaller>=6.16.0",
]

[build-system]
requires = ["pdm-backend >= 2.4.0"]
build-backend = "pdm.backend"

[tool.setuptools]
py-modules = []

[tool.uv]
# We want to use copy here, since symlink mode means we can't use our own portaudio dll
# A bit slower, but it works for our use case
link-mode = "copy"
default-groups = []

[project.scripts]
lightshow = "lightshow.__main__:main"
