name: Build and Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v7.1.3
        with:
          enable-cache: true

      - name: Install NSIS (Choco)
        shell: pwsh
        run: |
          choco install nsis
          echo "C:\Program Files (x86)\NSIS\Bin" | Out-File -FilePath "$env:GITHUB_PATH" -Append
          echo "C:\Program Files (x86)\NSIS" | Out-File -FilePath "$env:GITHUB_PATH" -Append

      - name: Update Path for Windows
        run: echo "$APPDATA\Python\Scripts" >> $GITHUB_PATH

      - name: Enable long paths for git on Windows
        run: git config --system core.longpaths true

      - name: Install dependencies
        run: uv sync --locked --all-extras

      - name: Build with PyInstaller
        run: uv run pyinstaller lightshow.spec

      - name: Create installer
        run: |
          cd installer && makensis /DPRODUCT_VERSION=${{ github.run_number }} lightshow.nsi

      - name: Get previous release tag
        id: prev_release
        run: |
          TAG=$(gh api repos/${{ github.repository }}/releases --jq ".[0].tag_name" || echo "")
          echo "tag=$TAG" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate changelog
        id: changelog
        run: |
          if [ -z "${{ steps.prev_release.outputs.tag }}" ]; then
            echo "No previous release found. Showing commits from start."
            git log --pretty=format:"- %s (%h)" > CHANGELOG.md
          else
            echo "Previous release: ${{ steps.prev_release.outputs.tag }}"
            git log ${{ steps.prev_release.outputs.tag }}..HEAD --pretty=format:"- %s (%h)" > CHANGELOG.md
          fi
      - name: Create Release
        uses: softprops/action-gh-release@v2.4.2
        with:
          tag_name: v${{ github.run_number }}
          files: installer/lightshow-setup-win-${{ github.run_number }}.exe
          body_path: CHANGELOG.md
